[package]
name = "tee-agent"
version.workspace = true
edition.workspace = true

[lib]
name = "tee_agent"
path = "src/lib.rs"

[[bin]]
name = "tee-agent"
path = "src/main.rs"

[dependencies]
attester.workspace = true
base64 = "0.22"
decrypt-fs.workspace = true
executor.workspace = true
key-manager.workspace = true
tee-verifier.workspace = true
compute-controller.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
sha2.workspace = true
x25519-dalek = { workspace = true, features = ["static_secrets"] }
rand.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
kbs-types = "0.14"

[dev-dependencies]
cced.workspace = true
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
axum.workspace = true
