[package]
name = "key-manager"
version.workspace = true
edition.workspace = true

[dependencies]
hkdf.workspace = true
sha2.workspace = true
hex.workspace = true
serde.workspace = true
thiserror.workspace = true
x25519-dalek = { workspace = true, features = ["static_secrets"] }
aes-gcm.workspace = true
rand.workspace = true
dstack-sdk = { git = "https://github.com/Dstack-TEE/dstack.git", rev = "d3275d1", version = "0.1.2" }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
serde_json.workspace = true
