[package]
name = "cced"
version.workspace = true
edition.workspace = true

[lib]
name = "cced"
path = "src/lib.rs"

[[bin]]
name = "cced"
path = "src/main.rs"

[features]
dcap = ["tee-verifier/dcap"]

[dependencies]
key-manager.workspace = true
compute-controller.workspace = true
output-gate.workspace = true
tee-verifier.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum.workspace = true
aes-gcm.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
async-trait.workspace = true
sha2.workspace = true
hex.workspace = true
hmac.workspace = true
base64 = "0.22"
k256.workspace = true
sha3.workspace = true
uuid.workspace = true
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
rust-s3 = "0.37.1"
dotenvy = "0.15.7"
hkdf.workspace = true

[dev-dependencies]
x25519-dalek = { workspace = true, features = ["static_secrets"] }
tower = { version = "0.5", features = ["util"] }
testcontainers.workspace = true
